trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'build'
    displayName: 'Build & Publish'
    jobs:
      - job: 'Build'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET 8.x'
            inputs:
              packageType: 'sdk'
              version: '8.x'
          - task: PowerShell@2
            displayName: 'Run Build and Publish with NUKE'
            inputs:
              filePath: './build.ps1'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathToPublish: '$(Build.SourcesDirectory)/output'
              ArtifactName: 'build-output'
              publishLocation: 'Container'
  - stage: 'int'
    displayName: 'INT'
    dependsOn: [ 'build' ]
    
    jobs:
      - deployment: 'INT'
        environment:
          name: 'INT'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Deploy to App Service'
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'TemplateAppSC'
                    appType: 'webAppLinux'
                    WebAppName: 'templateapp-int-webapp'
                    packageForLinux: '$(Agent.BuildDirectory)/build-output/App'
                    RuntimeStack: 'DOTNETCORE|8.0'
