trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'build'
    displayName: 'Build & Publish'
    jobs:
      - job: 'Build'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET 8.x'
            inputs:
              packageType: 'sdk'
              version: '8.x'
          - task: PowerShell@2
            inputs:
              filePath: './build.ps1'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/output'
              ArtifactName: 'build-output'
              publishLocation: 'Container'
