trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'build'
    displayName: 'Build & Publish'
    jobs:
      - job: 'Build'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET 8.x'
            inputs:
              packageType: 'sdk'
              version: '8.x'
          - task: PowerShell@2
            displayName: 'Run Build and Publish with NUKE'
            inputs:
              filePath: './build.ps1'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathToPublish: '$(Build.SourcesDirectory)/output'
              ArtifactName: 'build-output'
              publishLocation: 'Container'
  - stage: 'INT'
    displayName: 'INT'
    dependsOn: [ 'build' ]
    jobs:
      - template: 'deploy-template.yml'
        parameters:
          environment: 'INT'
          serviceConnectionName: 'TemplateAppSC'
          webAppName: 'templateapp-int-webapp'
